### ISSUE TITLE
py3k coverage not 100%

### ISSUE THREAD

**Issue by tisdall** [Pylons/colander#226] opened 2015-05-13 16:43 UTC
```
$ env/bin/nosetests --with-xunit --with-xcoverage --cover-min-percentage=100
Name                           Stmts   Miss  Cover   Missing
------------------------------------------------------------
colander                         989      2    99%   2207-2208
colander.compat                    9      0   100%   
colander.iso8601                   4      0   100%   
colander.tests                     1      0   100%   
colander.tests.test_colander    2786      0   100%   
colander.tests.test_iso8601      145      0   100%   
------------------------------------------------------------
TOTAL                           3934      2    99%   
nose.plugins.cover: ERROR: TOTAL Coverage did not reach minimum required: 100%
```

The code in question is:
```python
        try:
            functools.update_wrapper(self, wrapped)
        except AttributeError: #non-function
            self.__doc__ = getattr(wrapped, '__doc__', None)
```

And the reason can be [found in the docs](https://docs.python.org/3/library/functools.html#functools.update_wrapper):
> Changed in version 3.2: Missing attributes no longer trigger an AttributeError.

**Comment by mmerickel** [comment] 2016-01-16 21:43
Coverage is being tested on py35 and py27 with a combined 100% right now. Closing this as a non-issue.

**Closed by mmerickel** 2016-01-16 21:43 UTC

**Comment by tisdall** [comment] 2016-01-18 01:08
I'm a little curious how that works now...  I think 3.5 still doesn't raise that exception so the code isn't run in 3.5, but Travis shows that it's reporting 100%.

**Comment by mmerickel** [comment] 2016-01-18 02:07
Sorry I have no idea what you just said about 3.5.

**Comment by bertjwregeer** [comment] 2016-01-18 02:47
He is saying that under Python 3.5 the `except AttributeError` never gets raised, and thus Python 3.5 won't have full test coverage (which is correct...)

What he seems to be confused about is how we merge the test results from Python 2.7 and Python 3.5 to come to a combined total of 100% test coverage.

**Comment by tisdall** [comment] 2016-01-18 03:18
Looking at `coverage` code I think it may be combining it in the simplest manner possible.  So 100% coverage occurs if ***any*** of the coverage files covers every line of code, not that ***every*** coverage file covers every line of code.  I have a suspicion that if the py2 test covered 100% the py3 test could cover 0% and it'd still report 100%.

**Comment by bertjwregeer** [comment] 2016-01-18 04:24
Yes. That is by design. We don't attempt nor care to get to 100% code coverage in both Py2 and Py3. In the past we've "tried" and mostly gotten there by adding pragma: nocover to just Py2/Py3 code-paths giving us a false sense of security.

Unfortunately there are a variety of cases where 100% code coverage simply can't be achieved across both major versions, and that is not a use case we care to support either.

**Comment by tisdall** [comment] 2016-01-18 15:40
I was thinking about this last night...  The "pragma" comments are the default setting for marking lines as being excluded from coverage, but you can define something different (http://coverage.readthedocs.org/en/latest/excluding.html#advanced-exclusion).  It'd be possible to have a `.coveragerc_py3` and `.coveragerc_py2` and define some other sort of comment that would only exclude a line from the py3 tests or the py2 test.  Then that particular line could be excluded from only the py3 tests.

Just an FYI, I'm not sure if it's really worth doing.

**Comment by tisdall** [comment] 2020-02-25 14:41
[Ned posted about an interesting plugin](https://github.com/nedbat/coveragepy/issues/370#issuecomment-590860169) that would cover this kind of thing:  https://sobolevn.me/2020/02/conditional-coverage
